#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Mon Sep 30 15:19:27 2019
#

import wx
import control as ct

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Simulador(wx.Frame):
    def __init__(self, *args, **kwds):
        self.aux_id = 0
        self.processos = ct.ListaProcessos()
        self.bkp_procs = self.processos.copy()
        # begin wxGlade: Simulador.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1130, 543))
        self.lc_procs = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.bt_addProc = wx.Button(self.panel_1, wx.ID_ANY, "Adicionar Processo")
        self.bt_delProc = wx.Button(self.panel_1, wx.ID_ANY, "Remover Processo")
        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_5 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.tx_log = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.HSCROLL | wx.VSCROLL | wx.TE_BESTWRAP | wx.TE_MULTILINE | wx.TE_NO_VSCROLL | wx.TE_READONLY)
        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        self.bt_ex1proc = wx.Button(self.panel_2, wx.ID_ANY, "Executa 1 Processo")
        self.bt_extproc = wx.Button(self.panel_2, wx.ID_ANY, "Executa Todos Processos")
        self.panel_6 = wx.Panel(self.panel_2, wx.ID_ANY)
        self.bt_restart = wx.Button(self.panel_2, wx.ID_ANY, u"Reiniciar Simulação")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Simulador.__set_properties
        self.SetTitle("Simulador SJF")
        self.lc_procs.AppendColumn("ID", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lc_procs.AppendColumn("Tempo", format=wx.LIST_FORMAT_LEFT, width=-1)
        # end wxGlade
        self.bt_addProc.Bind(wx.EVT_BUTTON, self.onBtAddProc)
        self.bt_delProc.Bind(wx.EVT_BUTTON, self.onBtDelProc)
        self.bt_ex1proc.Bind(wx.EVT_BUTTON, self.onBtEx1Proc)
        self.bt_extproc.Bind(wx.EVT_BUTTON, self.onBtExTProc)
        self.bt_restart.Bind(wx.EVT_BUTTON, self.onBtRestart)

    def __do_layout(self):
        # begin wxGlade: Simulador.__do_layout
        grid_sizer_1 = wx.GridSizer(2, 2, 0, 0)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1.Add(self.lc_procs, 10, wx.ALIGN_RIGHT | wx.BOTTOM | wx.EXPAND, 0)
        sizer_2.Add(self.bt_addProc, 0, wx.FIXED_MINSIZE, 0)
        sizer_2.Add(self.bt_delProc, 0, wx.FIXED_MINSIZE, 0)
        sizer_2.Add(self.panel_4, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)
        sizer_2.Add(self.panel_5, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        grid_sizer_1.Add(self.panel_1, 1, wx.ALIGN_RIGHT | wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE, 7)
        grid_sizer_1.Add(self.tx_log, 0, wx.SHAPED, 0)
        sizer_1.Add(self.bt_ex1proc, 0, 0, 0)
        sizer_1.Add(self.bt_extproc, 0, 0, 0)
        sizer_1.Add(self.panel_6, 1, wx.EXPAND, 0)
        sizer_1.Add(self.bt_restart, 0, 0, 0)
        self.panel_2.SetSizer(sizer_1)
        grid_sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        self.Layout()
        # end wxGlade

    def onBtAddProc(self, e):
        nproc = ct.Processo(self.aux_id)
        self.aux_id += 1

        self.processos.add_proc(nproc)
        index = self.lc_procs.InsertItem(100000, str(nproc.idf))
        self.lc_procs.SetItem(index, 1, str(nproc.texec))
        self.bkp_procs = self.processos.copy()

    def onBtDelProc(self, e):
        index = self.lc_procs.GetFirstSelected()
        if index > -1:
            idf = int(self.lc_procs.GetItem(index).GetText())
            self.processos.del_proc(idf)
            self.lc_procs.DeleteItem(index)
            self.bkp_procs = self.processos.copy()
        else:
            wx.MessageBox('Selecione um processo para deletar', 'Erro', wx.OK | wx.ICON_ERROR)

    def onBtEx1Proc(self, e):
        self.processos.executar_ucp(self.showResult, self.showFila)

    def onBtExTProc(self, e):
        while self.processos.executar_ucp(self.showResult, self.showFila):
            self.tx_log.AppendText('\n')

    def onBtRestart(self, e):
        self.tx_log.Clear()
        self.processos = self.bkp_procs.copy()

    def showFila(self, fila):
        self.tx_log.AppendText(f'Fila: {fila}\n')

    def showResult(self, result):
        self.tx_log.AppendText(f'{result}\n')

# end of class Simulador


class MyApp(wx.App):
    def OnInit(self):
        self.frame = Simulador(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp


if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
